In [2]:
import numpy as np
#Two dimension array 
a=[[1,2,3],[4,5,6],[7,8,9]]
print(type(a))
myarray=np.array(a)
print(myarray)
#print(type(myarray))
print("3ed element of the 2 dimenson array is: ", myarray[0][2])

<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
3ed element of the 2 dimenson array is:  3
