In [2]:
import numpy as np
#**********Zero Array***********
ar=np.zeros(5) #this is one dimesnsion zero array
print("Print one dimensional array :",ar)
ar2=np.zeros((2,3))
print("Print two Dimension Array")
print(ar2)

Print one dimensional array : [0. 0. 0. 0. 0.]
Print two Dimension Array
[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
ar3=np.ones((3,2))#once array
ar3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
ar4=np.eye(4)# this will print identity matrix
ar4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
ar5=np.diag([1,2,3,4])# this will print digoanl array
ar5

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
#randint : use for get nardom number between given range
ar6=np.random.randint(1,10,3)
print(ar6)
#get random number
ar7=np.random.rand(1,5)
print(ar7)

[7 6 1]
[[0.30793676 0.85463581 0.43444938 0.79562744 0.85786823]]
