In [1]:
import numpy as np
#Reshaping of Array
#convert one dimestion arry into 2 or three dimension
#make a array of number b/w 1 to 10 and array have 12 element
arr=np.random.randint(1,10,12)
print("This is one dimensional Array", arr)
arr1=arr.reshape(2,6)#converted one dim arr into 2 dim arr of 2*6 matrix
print(arr1)
print("Converting one dimensional Array into two Dimension")
arr2=arr.reshape(6,-1)#-1 means it will chose next term for dimenstion
print(arr2)


This is one dimensional Array [9 8 2 9 1 7 3 4 4 4 4 5]
[[9 8 2 9 1 7]
 [3 4 4 4 4 5]]
Converting one dimensional Array into two Dimension
[[9 8]
 [2 9]
 [1 7]
 [3 4]
 [4 4]
 [4 5]]
