In [13]:
'''we can join array using 
1.> concatenate key word: join along with rows
2.>stack  :  join array alog with axis
3.>hstack : join array along row
4.>dstack : join along with heigh
5.>vstack : along with columns
'''

'we can join array useing \n1.> concatenate key word: join alog with rows\n2.>stack :join array alog with axis\n3.>hstack : join array along row\n4.>dstack : join along with heigh\n5.>vstack : along with columns\n'

In [7]:
import numpy as np
#**********Joining Array with concatenate key word*******
arr1=np.array([[1,2,3,5],[20,50,46,80]])
arr2=np.array([[4,5,6,7],[10,20,30,40]])
arr=np.concatenate((arr1,arr2))
print(arr)


[[ 1  2  3  5]
 [20 50 46 80]
 [ 4  5  6  7]
 [10 20 30 40]]


In [9]:
import numpy as np
#**********Joining Array with stak key work******* 
#*******stack join the arry along with axis*****both array have to same num of element
arr1=np.array([1,2,3,8])
arr2=np.array([4,5,6,7])
arr=np.stack((arr1,arr2))
print(arr)


[[1 2 3 8]
 [4 5 6 7]]


In [11]:
import numpy as np
#**********Joining Array with dtack*******
#****dstack join arry in collumn*****
arr1=np.array([1,2,3,8])
arr2=np.array([4,5,6,7])
arr=np.dstack((arr1,arr2))
print(arr)


[[[1 4]
  [2 5]
  [3 6]
  [8 7]]]
