In [ ]:
#Seaching in Array

#key words :

In [8]:
import numpy as np  
arr=np.array([1,2,3,4,5,6,7,8,9,4,4])
x=np.where(arr==4)
print(x)

(array([ 3,  9, 10], dtype=int32),)


In [3]:
import numpy as np  
arr=np.array([1,2,3,4,5,6,7,8,9,4,4])
x=np.where(arr%2==0)#Find the indexes where the values are even:
print(x)

(array([ 1,  3,  5,  7,  9, 10], dtype=int32),)


In [4]:
import numpy as np  
arr=np.array([1,2,3,4,5,6,7,8,9,4,4])
x=np.where(arr%2==1)#Find the indexes where the values are odd:
print(x)

(array([0, 2, 4, 6, 8], dtype=int32),)


In [17]:
#Search Sorted
'''There is a method called searchsorted() which performs a binary search in the array, 
and returns the index where the specified value would be inserted to maintain the search
 order.'''
import numpy as np  
arr=np.array([1,2,3,4,5,6,7,8,9,4,4])
x=np.searchsorted(arr,5, side='right')
y=np.searchsorted(arr,5, side='left')
print(x)
print(y)

5
4


In [19]:
import numpy as np  
arr=np.array([1,2,3,4,5,6,7,8,9,4,4])
x=np.searchsorted(arr,[4,2,5])#find the idexes where the multiple valuse are:
print(x)

[3 1 4]
