In [ ]:
#Random Number  

In [1]:
from numpy import random

x = random.randint(100,200,10)
print(x)

[146 133 119 152 173 130 139 126 147 188]


In [13]:
from numpy import random

x = random.randint(100, size=(5))
print(x)

[76 11 23 67  3]


In [15]:
from numpy import random
#Generate 2D array with 3 rwo and contaning 5 random interger from 0 to 100
x = random.randint(100, size=(3,5))
print(x)

[[47 70 10 50 31]
 [35 87 77 14 93]
 [19 92 26 42 70]]


In [19]:
from numpy import random
#rand() method giver vale near to zero
x = random.rand(1,10)
print(x)

[[0.74614973 0.03935098 0.48654574 0.34850561 0.4900693  0.69119509
  0.2482454  0.69985764 0.84429724 0.00820868]]


In [7]:
from numpy import random
#random.choice()
x = random.choice([1,2,3,4,5,6])
print(x)

6
