In [1]:
#Random Data Distribution

from numpy import random
x=random.choice([1,2,3,4,5], p=[0.1,0.2,0.3,0.4,0], size=20)
print(x)

[4 4 4 3 3 2 2 3 3 3 3 3 3 4 3 4 4 2 3 2]


In [8]:
from numpy import random
x=random.choice([1,2,3,4,5], p=[0.1,0.2,0.3,0.4,0], size=(3,5))
print(x)

[[4 3 4 3 4]
 [3 2 4 4 3]
 [1 4 2 3 2]]
