In [2]:
#Arthimatic Function with Numpy function
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
sum=np.add(arr1,arr2)
subtract=np.subtract(arr1,arr2)
multily=np.multiply(arr1,arr2)
divide=np.divide(arr1,arr2)
power=np.power(arr1,arr2)
mod=np.mod(arr1,arr2)
reminder=np.remainder(arr1,arr2)
print("sum :",sum)
print(subtract)
print(multily)
print(divide)
print(power)
print(mod)
print(reminder)


sum : [30 41 52 63 74 85]
[-10  -1   8  17  26  35]
[ 200  420  660  920 1200 1500]
[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]
[1661992960          0 1749024768          0 1090519040          0]
[10 20  8 17  2 10]
[10 20  8 17  2 10]
