In [2]:
import numpy as np  
#********Check shape of array*************
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


In [5]:
arr1=np.array([[7,8,9],[4,5,6],[1,2,3],[10,11,12]])

#*****Reshape array***********
print("Original shape is: ",arr1.shape)
print(arr1.reshape(3,4))

Original shape is:  (4, 3)
[[ 7  8  9  4]
 [ 5  6  1  2]
 [ 3 10 11 12]]


In [4]:
#***************Unkhown Dimension**********
import numpy as np
arr1=np.array([[7,8,9],[4,5,6],[1,2,3],[10,11,12]])
print(arr1.reshape(-1,2))#-1 means first dimension is not fixed
print("Reshape in other way")
print(arr1.reshape(4,-1))

[[ 7  8]
 [ 9  4]
 [ 5  6]
 [ 1  2]
 [ 3 10]
 [11 12]]
Reshape in other way
[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]


In [5]:
#Flattening the arrays
#Flattening array means converting a multidimensional array into a 1D array.
import numpy as np
arr1=np.array([[7,8,9],[4,5,6],[1,2,3],[10,11,12]])
print(arr1.reshape(-1))

[ 7  8  9  4  5  6  1  2  3 10 11 12]
